### ISSUE TITLE
rendu tp

### ISSUE THREAD

**Issue by podoko** [PolytechLyon/4a-isi3-tp2-2016-2017-groupe-1-bertrand_bontron-1#1]

**Comment by Slashgear** [comment]
❓ Il est où le affichageHauteur ?

👍 Sinon le reste est pas mal.

**Comment by podoko** [comment]
J'ai aucune idée de pourquoi le fichier a pas été ajouté, je l'ai remis hier.

**Comment by Slashgear** [comment]
Ok, et sinon la priorité des opérations ça marche ❓

**Comment by podoko** [comment]
On en a discuté avec Julien et on s'est dit que l'ordre de priorité dépend du sens de lecture. Pour l'arbre
```
*
|___+
|   |___1
|   |___5
|___-
    |___6
```
on peut par exemple lire `-6 * 1 +5` ou `-6 * 5 + 1` selon si on parcourt un nœud de gauche à droite ou de droite à gauche, alors on a pas trouvé naturel de tenter de mettre en place un système de priorité sur les opérations. Donc on considère qu'il y a des parenthèses entre chaque opérateur.
On lit par conséquent l'arbre comme ça : `(-6) * (1 + 5)` et normalement, oui ça fonctionne.

**Comment by Slashgear** [comment]
Après je vous note pas la dessus. 😉 C'était juste pour voir si vous vous étiez posé la questions ==> le boulot d'un ingénieur
